//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasterFloorApp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Adress
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Adress()
        {
            this.InfoPartner = new HashSet<InfoPartner>();
        }
    
        public int IdAdress { get; set; }
        public int IdIndex { get; set; }
        public int AreaId { get; set; }
        public int CityId { get; set; }
        public int StreetId { get; set; }
        public int HouseNumber { get; set; }
    
        public virtual Areas Areas { get; set; }
        public virtual Cities Cities { get; set; }
        public virtual Index Index { get; set; }
        public virtual Streets Streets { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoPartner> InfoPartner { get; set; }
    }
}
