//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasterFloorApp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class InfoPartner
    {
        public int IdInfoPartner { get; set; }
        public int IdPartnerType { get; set; }
        public int IdPartner { get; set; }
        public int IdDirector { get; set; }
        public string PartnerEmail { get; set; }
        public string Phone { get; set; }
        public int IdAdress { get; set; }
        public int IdINN { get; set; }
        public int Rating { get; set; }
    
        public virtual Adress Adress { get; set; }
        public virtual Directors Directors { get; set; }
        public virtual INN INN { get; set; }
        public virtual Partner Partner { get; set; }
        public virtual PartnerType PartnerType { get; set; }
    }
}
