//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasterFloorApp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class InfoProduct
    {
        public int IdInfoProduct { get; set; }
        public int IdProduct { get; set; }
        public int IdPartner { get; set; }
        public int ProductAmount { get; set; }
        public System.DateTime SaleDate { get; set; }
    
        public virtual Partner Partner { get; set; }
        public virtual Products Products { get; set; }
    }
}
