//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasterFloorApp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TypeProductRate
    {
        public int IdTypeProductRate { get; set; }
        public int IdProductType { get; set; }
        public decimal RateProduct { get; set; }
    
        public virtual ProductType ProductType { get; set; }
    }
}
